project:
  type: website
  output-dir: docs

website:
  title: "Alexandra Stauffer - MUSA 5080 Portfolio"
  description: "empty" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes 
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: Week 1
          - href: weekly-notes/week-02-notes.qmd
            text: Week 2
      - text: Labs
        menu: 
          - href: labs/lab0_template.qmd
            text: "Lab 0"
          - href: labs/lab-01.qmd
            text: "Lab 1"

format:
  html:
    theme: superhero
    toc: true
    code-fold: true

execute:
  freeze: auto
